//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mAxCommerce.WCF.Aif {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CallContext", Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
    [System.SerializableAttribute()]
    public partial class CallContext : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LanguageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LogonAsUserField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PartitionKeyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.Dictionary<string, string> PropertyBagField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Company {
            get {
                return this.CompanyField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyField, value) != true)) {
                    this.CompanyField = value;
                    this.RaisePropertyChanged("Company");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Language {
            get {
                return this.LanguageField;
            }
            set {
                if ((object.ReferenceEquals(this.LanguageField, value) != true)) {
                    this.LanguageField = value;
                    this.RaisePropertyChanged("Language");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LogonAsUser {
            get {
                return this.LogonAsUserField;
            }
            set {
                if ((object.ReferenceEquals(this.LogonAsUserField, value) != true)) {
                    this.LogonAsUserField = value;
                    this.RaisePropertyChanged("LogonAsUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MessageId {
            get {
                return this.MessageIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageIdField, value) != true)) {
                    this.MessageIdField = value;
                    this.RaisePropertyChanged("MessageId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PartitionKey {
            get {
                return this.PartitionKeyField;
            }
            set {
                if ((object.ReferenceEquals(this.PartitionKeyField, value) != true)) {
                    this.PartitionKeyField = value;
                    this.RaisePropertyChanged("PartitionKey");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<string, string> PropertyBag {
            get {
                return this.PropertyBagField;
            }
            set {
                if ((object.ReferenceEquals(this.PropertyBagField, value) != true)) {
                    this.PropertyBagField = value;
                    this.RaisePropertyChanged("PropertyBag");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="XppObjectBase", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.Ax.Xpp")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(mAxCommerce.WCF.Aif.mAxCommerceCategory))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(mAxCommerce.WCF.Aif.mAxCommerceOrder))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(mAxCommerce.WCF.Aif.mAxCommerceOrderLine))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(mAxCommerce.WCF.Aif.mAxCommerceProduct))]
    public partial class XppObjectBase : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mAxCommerceCategory", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class mAxCommerceCategory : mAxCommerce.WCF.Aif.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private mAxCommerce.WCF.Aif.mAxCommerceCategory[] parmChildCategoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long parmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmNameField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public mAxCommerce.WCF.Aif.mAxCommerceCategory[] parmChildCategories {
            get {
                return this.parmChildCategoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.parmChildCategoriesField, value) != true)) {
                    this.parmChildCategoriesField = value;
                    this.RaisePropertyChanged("parmChildCategories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parmId {
            get {
                return this.parmIdField;
            }
            set {
                if ((this.parmIdField.Equals(value) != true)) {
                    this.parmIdField = value;
                    this.RaisePropertyChanged("parmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmName {
            get {
                return this.parmNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parmNameField, value) != true)) {
                    this.parmNameField = value;
                    this.RaisePropertyChanged("parmName");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mAxCommerceOrder", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class mAxCommerceOrder : mAxCommerce.WCF.Aif.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmCountryField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private mAxCommerce.WCF.Aif.mAxCommerceOrderLine[] parmLinesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmStreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmZipCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmCity {
            get {
                return this.parmCityField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCityField, value) != true)) {
                    this.parmCityField = value;
                    this.RaisePropertyChanged("parmCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmCountry {
            get {
                return this.parmCountryField;
            }
            set {
                if ((object.ReferenceEquals(this.parmCountryField, value) != true)) {
                    this.parmCountryField = value;
                    this.RaisePropertyChanged("parmCountry");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmFirstName {
            get {
                return this.parmFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parmFirstNameField, value) != true)) {
                    this.parmFirstNameField = value;
                    this.RaisePropertyChanged("parmFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmLastName {
            get {
                return this.parmLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parmLastNameField, value) != true)) {
                    this.parmLastNameField = value;
                    this.RaisePropertyChanged("parmLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public mAxCommerce.WCF.Aif.mAxCommerceOrderLine[] parmLines {
            get {
                return this.parmLinesField;
            }
            set {
                if ((object.ReferenceEquals(this.parmLinesField, value) != true)) {
                    this.parmLinesField = value;
                    this.RaisePropertyChanged("parmLines");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmStreet {
            get {
                return this.parmStreetField;
            }
            set {
                if ((object.ReferenceEquals(this.parmStreetField, value) != true)) {
                    this.parmStreetField = value;
                    this.RaisePropertyChanged("parmStreet");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmZipCode {
            get {
                return this.parmZipCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.parmZipCodeField, value) != true)) {
                    this.parmZipCodeField = value;
                    this.RaisePropertyChanged("parmZipCode");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mAxCommerceOrderLine", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class mAxCommerceOrderLine : mAxCommerce.WCF.Aif.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long parmProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal parmQtyField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parmProductId {
            get {
                return this.parmProductIdField;
            }
            set {
                if ((this.parmProductIdField.Equals(value) != true)) {
                    this.parmProductIdField = value;
                    this.RaisePropertyChanged("parmProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal parmQty {
            get {
                return this.parmQtyField;
            }
            set {
                if ((this.parmQtyField.Equals(value) != true)) {
                    this.parmQtyField = value;
                    this.RaisePropertyChanged("parmQty");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="mAxCommerceProduct", Namespace="http://schemas.datacontract.org/2004/07/Dynamics.Ax.Application")]
    [System.SerializableAttribute()]
    public partial class mAxCommerceProduct : mAxCommerce.WCF.Aif.XppObjectBase {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmDescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long parmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long[] parmImagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string parmNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal parmPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmDescription {
            get {
                return this.parmDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.parmDescriptionField, value) != true)) {
                    this.parmDescriptionField = value;
                    this.RaisePropertyChanged("parmDescription");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long parmId {
            get {
                return this.parmIdField;
            }
            set {
                if ((this.parmIdField.Equals(value) != true)) {
                    this.parmIdField = value;
                    this.RaisePropertyChanged("parmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long[] parmImages {
            get {
                return this.parmImagesField;
            }
            set {
                if ((object.ReferenceEquals(this.parmImagesField, value) != true)) {
                    this.parmImagesField = value;
                    this.RaisePropertyChanged("parmImages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string parmName {
            get {
                return this.parmNameField;
            }
            set {
                if ((object.ReferenceEquals(this.parmNameField, value) != true)) {
                    this.parmNameField = value;
                    this.RaisePropertyChanged("parmName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal parmPrice {
            get {
                return this.parmPriceField;
            }
            set {
                if ((this.parmPriceField.Equals(value) != true)) {
                    this.parmPriceField = value;
                    this.RaisePropertyChanged("parmPrice");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class AifFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomDetailXmlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private mAxCommerce.WCF.Aif.FaultMessageList[] FaultMessageListArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private mAxCommerce.WCF.Aif.InfologMessage[] InfologMessageListField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int XppExceptionTypeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomDetailXml {
            get {
                return this.CustomDetailXmlField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomDetailXmlField, value) != true)) {
                    this.CustomDetailXmlField = value;
                    this.RaisePropertyChanged("CustomDetailXml");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public mAxCommerce.WCF.Aif.FaultMessageList[] FaultMessageListArray {
            get {
                return this.FaultMessageListArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageListArrayField, value) != true)) {
                    this.FaultMessageListArrayField = value;
                    this.RaisePropertyChanged("FaultMessageListArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public mAxCommerce.WCF.Aif.InfologMessage[] InfologMessageList {
            get {
                return this.InfologMessageListField;
            }
            set {
                if ((object.ReferenceEquals(this.InfologMessageListField, value) != true)) {
                    this.InfologMessageListField = value;
                    this.RaisePropertyChanged("InfologMessageList");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int XppExceptionType {
            get {
                return this.XppExceptionTypeField;
            }
            set {
                if ((this.XppExceptionTypeField.Equals(value) != true)) {
                    this.XppExceptionTypeField = value;
                    this.RaisePropertyChanged("XppExceptionType");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessageList", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessageList : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DocumentOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private mAxCommerce.WCF.Aif.FaultMessage[] FaultMessageArrayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FieldField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceOperationParameterField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XPathField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlLineField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string XmlPositionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Document {
            get {
                return this.DocumentField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentField, value) != true)) {
                    this.DocumentField = value;
                    this.RaisePropertyChanged("Document");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DocumentOperation {
            get {
                return this.DocumentOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.DocumentOperationField, value) != true)) {
                    this.DocumentOperationField = value;
                    this.RaisePropertyChanged("DocumentOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public mAxCommerce.WCF.Aif.FaultMessage[] FaultMessageArray {
            get {
                return this.FaultMessageArrayField;
            }
            set {
                if ((object.ReferenceEquals(this.FaultMessageArrayField, value) != true)) {
                    this.FaultMessageArrayField = value;
                    this.RaisePropertyChanged("FaultMessageArray");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Field {
            get {
                return this.FieldField;
            }
            set {
                if ((object.ReferenceEquals(this.FieldField, value) != true)) {
                    this.FieldField = value;
                    this.RaisePropertyChanged("Field");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Service {
            get {
                return this.ServiceField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceField, value) != true)) {
                    this.ServiceField = value;
                    this.RaisePropertyChanged("Service");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperation {
            get {
                return this.ServiceOperationField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationField, value) != true)) {
                    this.ServiceOperationField = value;
                    this.RaisePropertyChanged("ServiceOperation");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceOperationParameter {
            get {
                return this.ServiceOperationParameterField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceOperationParameterField, value) != true)) {
                    this.ServiceOperationParameterField = value;
                    this.RaisePropertyChanged("ServiceOperationParameter");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XPath {
            get {
                return this.XPathField;
            }
            set {
                if ((object.ReferenceEquals(this.XPathField, value) != true)) {
                    this.XPathField = value;
                    this.RaisePropertyChanged("XPath");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlLine {
            get {
                return this.XmlLineField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlLineField, value) != true)) {
                    this.XmlLineField = value;
                    this.RaisePropertyChanged("XmlLine");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string XmlPosition {
            get {
                return this.XmlPositionField;
            }
            set {
                if ((object.ReferenceEquals(this.XmlPositionField, value) != true)) {
                    this.XmlPositionField = value;
                    this.RaisePropertyChanged("XmlPosition");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessage", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    [System.SerializableAttribute()]
    public partial class InfologMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private mAxCommerce.WCF.Aif.InfologMessageType InfologMessageTypeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public mAxCommerce.WCF.Aif.InfologMessageType InfologMessageType {
            get {
                return this.InfologMessageTypeField;
            }
            set {
                if ((this.InfologMessageTypeField.Equals(value) != true)) {
                    this.InfologMessageTypeField = value;
                    this.RaisePropertyChanged("InfologMessageType");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultMessage", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
    [System.SerializableAttribute()]
    public partial class FaultMessage : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code {
            get {
                return this.CodeField;
            }
            set {
                if ((object.ReferenceEquals(this.CodeField, value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfologMessageType", Namespace="http://schemas.datacontract.org/2004/07/Microsoft.Dynamics.AX.Framework.Services")]
    public enum InfologMessageType : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Info = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Warning = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Error = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org", ConfigurationName="Aif.mAxCommerceService")]
    public interface mAxCommerceService {
        
        // CODEGEN: Generating message contract since the wrapper name (mAxCommerceServiceGetProductByIdRequest) of message mAxCommerceServiceGetProductByIdRequest does not match the default value (getProductById)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mAxCommerceService/getProductById", ReplyAction="http://tempuri.org/mAxCommerceService/getProductByIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(mAxCommerce.WCF.Aif.AifFault), Action="http://tempuri.org/mAxCommerceService/getProductByIdAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdResponse getProductById(mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mAxCommerceService/getProductById", ReplyAction="http://tempuri.org/mAxCommerceService/getProductByIdResponse")]
        System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdResponse> getProductByIdAsync(mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (mAxCommerceServiceCreateOrderRequest) of message mAxCommerceServiceCreateOrderRequest does not match the default value (createOrder)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mAxCommerceService/createOrder", ReplyAction="http://tempuri.org/mAxCommerceService/createOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(mAxCommerce.WCF.Aif.AifFault), Action="http://tempuri.org/mAxCommerceService/createOrderAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderResponse createOrder(mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mAxCommerceService/createOrder", ReplyAction="http://tempuri.org/mAxCommerceService/createOrderResponse")]
        System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderResponse> createOrderAsync(mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (mAxCommerceServiceGetCategoriesRequest) of message mAxCommerceServiceGetCategoriesRequest does not match the default value (getCategories)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mAxCommerceService/getCategories", ReplyAction="http://tempuri.org/mAxCommerceService/getCategoriesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(mAxCommerce.WCF.Aif.AifFault), Action="http://tempuri.org/mAxCommerceService/getCategoriesAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesResponse getCategories(mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mAxCommerceService/getCategories", ReplyAction="http://tempuri.org/mAxCommerceService/getCategoriesResponse")]
        System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesResponse> getCategoriesAsync(mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesRequest request);
        
        // CODEGEN: Generating message contract since the wrapper name (mAxCommerceServiceGetProductImageBase64Request) of message mAxCommerceServiceGetProductImageBase64Request does not match the default value (getProductImageBase64)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mAxCommerceService/getProductImageBase64", ReplyAction="http://tempuri.org/mAxCommerceService/getProductImageBase64Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(mAxCommerce.WCF.Aif.AifFault), Action="http://tempuri.org/mAxCommerceService/getProductImageBase64AifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Response getProductImageBase64(mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mAxCommerceService/getProductImageBase64", ReplyAction="http://tempuri.org/mAxCommerceService/getProductImageBase64Response")]
        System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Response> getProductImageBase64Async(mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Request request);
        
        // CODEGEN: Generating message contract since the wrapper name (mAxCommerceServiceGetProductsByCategoryRequest) of message mAxCommerceServiceGetProductsByCategoryRequest does not match the default value (getProductsByCategory)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mAxCommerceService/getProductsByCategory", ReplyAction="http://tempuri.org/mAxCommerceService/getProductsByCategoryResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(mAxCommerce.WCF.Aif.AifFault), Action="http://tempuri.org/mAxCommerceService/getProductsByCategoryAifFaultFault", Name="AifFault", Namespace="http://schemas.microsoft.com/dynamics/2008/01/documents/Fault")]
        mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryResponse getProductsByCategory(mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/mAxCommerceService/getProductsByCategory", ReplyAction="http://tempuri.org/mAxCommerceService/getProductsByCategoryResponse")]
        System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryResponse> getProductsByCategoryAsync(mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mAxCommerceServiceGetProductByIdRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class mAxCommerceServiceGetProductByIdRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public mAxCommerce.WCF.Aif.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public long productId;
        
        public mAxCommerceServiceGetProductByIdRequest() {
        }
        
        public mAxCommerceServiceGetProductByIdRequest(mAxCommerce.WCF.Aif.CallContext CallContext, long productId) {
            this.CallContext = CallContext;
            this.productId = productId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mAxCommerceServiceGetProductByIdResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class mAxCommerceServiceGetProductByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public mAxCommerce.WCF.Aif.mAxCommerceProduct response;
        
        public mAxCommerceServiceGetProductByIdResponse() {
        }
        
        public mAxCommerceServiceGetProductByIdResponse(mAxCommerce.WCF.Aif.mAxCommerceProduct response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mAxCommerceServiceCreateOrderRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class mAxCommerceServiceCreateOrderRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public mAxCommerce.WCF.Aif.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public mAxCommerce.WCF.Aif.mAxCommerceOrder orderDto;
        
        public mAxCommerceServiceCreateOrderRequest() {
        }
        
        public mAxCommerceServiceCreateOrderRequest(mAxCommerce.WCF.Aif.CallContext CallContext, mAxCommerce.WCF.Aif.mAxCommerceOrder orderDto) {
            this.CallContext = CallContext;
            this.orderDto = orderDto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mAxCommerceServiceCreateOrderResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class mAxCommerceServiceCreateOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public mAxCommerceServiceCreateOrderResponse() {
        }
        
        public mAxCommerceServiceCreateOrderResponse(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mAxCommerceServiceGetCategoriesRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class mAxCommerceServiceGetCategoriesRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public mAxCommerce.WCF.Aif.CallContext CallContext;
        
        public mAxCommerceServiceGetCategoriesRequest() {
        }
        
        public mAxCommerceServiceGetCategoriesRequest(mAxCommerce.WCF.Aif.CallContext CallContext) {
            this.CallContext = CallContext;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mAxCommerceServiceGetCategoriesResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class mAxCommerceServiceGetCategoriesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public mAxCommerce.WCF.Aif.mAxCommerceCategory response;
        
        public mAxCommerceServiceGetCategoriesResponse() {
        }
        
        public mAxCommerceServiceGetCategoriesResponse(mAxCommerce.WCF.Aif.mAxCommerceCategory response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mAxCommerceServiceGetProductImageBase64Request", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class mAxCommerceServiceGetProductImageBase64Request {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public mAxCommerce.WCF.Aif.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public long imageId;
        
        public mAxCommerceServiceGetProductImageBase64Request() {
        }
        
        public mAxCommerceServiceGetProductImageBase64Request(mAxCommerce.WCF.Aif.CallContext CallContext, long imageId) {
            this.CallContext = CallContext;
            this.imageId = imageId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mAxCommerceServiceGetProductImageBase64Response", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class mAxCommerceServiceGetProductImageBase64Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public string response;
        
        public mAxCommerceServiceGetProductImageBase64Response() {
        }
        
        public mAxCommerceServiceGetProductImageBase64Response(string response) {
            this.response = response;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mAxCommerceServiceGetProductsByCategoryRequest", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class mAxCommerceServiceGetProductsByCategoryRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://schemas.microsoft.com/dynamics/2010/01/datacontracts")]
        public mAxCommerce.WCF.Aif.CallContext CallContext;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public long categoryId;
        
        public mAxCommerceServiceGetProductsByCategoryRequest() {
        }
        
        public mAxCommerceServiceGetProductsByCategoryRequest(mAxCommerce.WCF.Aif.CallContext CallContext, long categoryId) {
            this.CallContext = CallContext;
            this.categoryId = categoryId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="mAxCommerceServiceGetProductsByCategoryResponse", WrapperNamespace="http://tempuri.org", IsWrapped=true)]
    public partial class mAxCommerceServiceGetProductsByCategoryResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org", Order=0)]
        public mAxCommerce.WCF.Aif.mAxCommerceProduct[] response;
        
        public mAxCommerceServiceGetProductsByCategoryResponse() {
        }
        
        public mAxCommerceServiceGetProductsByCategoryResponse(mAxCommerce.WCF.Aif.mAxCommerceProduct[] response) {
            this.response = response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface mAxCommerceServiceChannel : mAxCommerce.WCF.Aif.mAxCommerceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class mAxCommerceServiceClient : System.ServiceModel.ClientBase<mAxCommerce.WCF.Aif.mAxCommerceService>, mAxCommerce.WCF.Aif.mAxCommerceService {
        
        public mAxCommerceServiceClient() {
        }
        
        public mAxCommerceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public mAxCommerceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mAxCommerceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public mAxCommerceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdResponse mAxCommerce.WCF.Aif.mAxCommerceService.getProductById(mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdRequest request) {
            return base.Channel.getProductById(request);
        }
        
        public mAxCommerce.WCF.Aif.mAxCommerceProduct getProductById(mAxCommerce.WCF.Aif.CallContext CallContext, long productId) {
            mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdRequest inValue = new mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdRequest();
            inValue.CallContext = CallContext;
            inValue.productId = productId;
            mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdResponse retVal = ((mAxCommerce.WCF.Aif.mAxCommerceService)(this)).getProductById(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdResponse> mAxCommerce.WCF.Aif.mAxCommerceService.getProductByIdAsync(mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdRequest request) {
            return base.Channel.getProductByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdResponse> getProductByIdAsync(mAxCommerce.WCF.Aif.CallContext CallContext, long productId) {
            mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdRequest inValue = new mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductByIdRequest();
            inValue.CallContext = CallContext;
            inValue.productId = productId;
            return ((mAxCommerce.WCF.Aif.mAxCommerceService)(this)).getProductByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderResponse mAxCommerce.WCF.Aif.mAxCommerceService.createOrder(mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderRequest request) {
            return base.Channel.createOrder(request);
        }
        
        public string createOrder(mAxCommerce.WCF.Aif.CallContext CallContext, mAxCommerce.WCF.Aif.mAxCommerceOrder orderDto) {
            mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderRequest inValue = new mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderRequest();
            inValue.CallContext = CallContext;
            inValue.orderDto = orderDto;
            mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderResponse retVal = ((mAxCommerce.WCF.Aif.mAxCommerceService)(this)).createOrder(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderResponse> mAxCommerce.WCF.Aif.mAxCommerceService.createOrderAsync(mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderRequest request) {
            return base.Channel.createOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderResponse> createOrderAsync(mAxCommerce.WCF.Aif.CallContext CallContext, mAxCommerce.WCF.Aif.mAxCommerceOrder orderDto) {
            mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderRequest inValue = new mAxCommerce.WCF.Aif.mAxCommerceServiceCreateOrderRequest();
            inValue.CallContext = CallContext;
            inValue.orderDto = orderDto;
            return ((mAxCommerce.WCF.Aif.mAxCommerceService)(this)).createOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesResponse mAxCommerce.WCF.Aif.mAxCommerceService.getCategories(mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesRequest request) {
            return base.Channel.getCategories(request);
        }
        
        public mAxCommerce.WCF.Aif.mAxCommerceCategory getCategories(mAxCommerce.WCF.Aif.CallContext CallContext) {
            mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesRequest inValue = new mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesRequest();
            inValue.CallContext = CallContext;
            mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesResponse retVal = ((mAxCommerce.WCF.Aif.mAxCommerceService)(this)).getCategories(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesResponse> mAxCommerce.WCF.Aif.mAxCommerceService.getCategoriesAsync(mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesRequest request) {
            return base.Channel.getCategoriesAsync(request);
        }
        
        public System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesResponse> getCategoriesAsync(mAxCommerce.WCF.Aif.CallContext CallContext) {
            mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesRequest inValue = new mAxCommerce.WCF.Aif.mAxCommerceServiceGetCategoriesRequest();
            inValue.CallContext = CallContext;
            return ((mAxCommerce.WCF.Aif.mAxCommerceService)(this)).getCategoriesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Response mAxCommerce.WCF.Aif.mAxCommerceService.getProductImageBase64(mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Request request) {
            return base.Channel.getProductImageBase64(request);
        }
        
        public string getProductImageBase64(mAxCommerce.WCF.Aif.CallContext CallContext, long imageId) {
            mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Request inValue = new mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Request();
            inValue.CallContext = CallContext;
            inValue.imageId = imageId;
            mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Response retVal = ((mAxCommerce.WCF.Aif.mAxCommerceService)(this)).getProductImageBase64(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Response> mAxCommerce.WCF.Aif.mAxCommerceService.getProductImageBase64Async(mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Request request) {
            return base.Channel.getProductImageBase64Async(request);
        }
        
        public System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Response> getProductImageBase64Async(mAxCommerce.WCF.Aif.CallContext CallContext, long imageId) {
            mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Request inValue = new mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductImageBase64Request();
            inValue.CallContext = CallContext;
            inValue.imageId = imageId;
            return ((mAxCommerce.WCF.Aif.mAxCommerceService)(this)).getProductImageBase64Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryResponse mAxCommerce.WCF.Aif.mAxCommerceService.getProductsByCategory(mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryRequest request) {
            return base.Channel.getProductsByCategory(request);
        }
        
        public mAxCommerce.WCF.Aif.mAxCommerceProduct[] getProductsByCategory(mAxCommerce.WCF.Aif.CallContext CallContext, long categoryId) {
            mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryRequest inValue = new mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryRequest();
            inValue.CallContext = CallContext;
            inValue.categoryId = categoryId;
            mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryResponse retVal = ((mAxCommerce.WCF.Aif.mAxCommerceService)(this)).getProductsByCategory(inValue);
            return retVal.response;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryResponse> mAxCommerce.WCF.Aif.mAxCommerceService.getProductsByCategoryAsync(mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryRequest request) {
            return base.Channel.getProductsByCategoryAsync(request);
        }
        
        public System.Threading.Tasks.Task<mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryResponse> getProductsByCategoryAsync(mAxCommerce.WCF.Aif.CallContext CallContext, long categoryId) {
            mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryRequest inValue = new mAxCommerce.WCF.Aif.mAxCommerceServiceGetProductsByCategoryRequest();
            inValue.CallContext = CallContext;
            inValue.categoryId = categoryId;
            return ((mAxCommerce.WCF.Aif.mAxCommerceService)(this)).getProductsByCategoryAsync(inValue);
        }
    }
}
